name: Simulate activity
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs: {}

jobs:
  simulate-activity:
    name: Simulate activity to keep workflows runnign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Amend and push force last commit to keep it up to date.
        run: |
          git commit --amend --no-edit
          git push --force origin master
